

title: Aravind On Software
email: hirearavindhu@gmail.com
description: ""
baseurl: ""
url: "https://aravindhu.com"
twitter_username: aravindhu
github_username:  aravind666
google_analytics: UA-53462338-1

# Build settings
exclude: [.idea]
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: katex
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
